// // import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";
// // // import TopBar from "@/components/Topbar";
// // import Navbar from "@/components/Navbar";
// // import Footer from "@/components/Footer";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable}`}
// //       >
// //         {/* <TopBar/> */}
// //         <Navbar/>
// //         {children}
// //         <Footer/>
// //       </body>
// //     </html>
// //   );
// // }



// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";
// import TopBar from "@/components/Topbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable}`}
//       >
//      <div className="w-full">

//   {/* TOP BAR */}
//   <TopBar />

//   {/* SOFT BACKGROUND SECTION */}
//   <div className="relative bg-gradient-to-b from-[#fdfbed] to-[#e3f0e9] pb-16 pt-10">

//     {/* FLOATING CAPSULE NAVBAR */}
//     <div className="max-w-7xl mx-auto">
//       <Navbar />
//     </div>

//   </div>
// </div>


//         {/* Main Content */}
//         <main className="flex-grow">{children}</main>

//         {/* Footer with spacing and rounded corners visible */}
//         <Footer />
//       </body>
//     </html>
//   );
// }


// app/layout.tsx

import "./globals.css";
import TopBar from "@/components/Topbar";
import Navbar from "@/components/Navbar";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* TOP DARK BAR */}
        <TopBar />

        {/* BACKGROUND BEHIND THE CAPSULE NAV */}
        {/* <div className="relative bg-[#ffff] bg-gradient-to-b from-[#ffff] to-[#ffff] pb-14">
          <Navbar className="sticky top-0 z-50" />
        </div> */}


        <Navbar />


        {/* PAGE CONTENT */}
        {children}
        {/* <Footer/> */}
      </body>
    </html>
  );
}
