// export interface assetImageType {
//     _type: string,
//     _ref: string,
// };
export interface AssetImageType {
  _ref: string;         // Sanity image reference
  _type: "reference";
  url: string;          // always "reference"
}

export interface ImageType {
  _type: "image";       // always "image"
  asset: AssetImageType;
  alt?: string;         // optional alt text
  _key: string;         // unique key generated by Sanity
}


export interface oneProductType {
  _id: string;
  _type: string;
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;  // Changed from productName
  basePrice?: number;  // Changed from price, made optional
  slug: any;
  shortDescription?: string;
  longDescription?: any;
  boxType?: string;
  industry?: string[];
  material?: string;
  dimensions?: {
    width: number;
    height: number;
    depth: number;
  };
  finishOptions?: string[];
  moq?: number;
  leadTime?: string;
  image: ImageType[];
  isFeatured?: boolean;
  createdAt?: string;
}

export interface responseType {
  result: Array<oneProductType>
}